spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Allure00/spring-cloud-config-repo
          username: 15238222651
          password: Allure123
          basedir: /usr/local/spring-cloud/spring-cloud-config/basedir  #F:\spring-cloud-config\basedir
  rabbitmq:
    host: 47.101.197.240
    port: 5672
    password: guest
    username: guest
eureka:
  client:
    service-url:
      defaultZone: http://47.101.197.240:8761/eureka
#关闭安全认证
management:
  #refresh接入点显式暴露出来
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8090

