server:
  port: 8090
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Allure00/spring-cloud-config-repo
          username: 15238222651
          password: Allure123
          # C:\Users\Administrator\Desktop\springcloud\spring-cloud-config\basedir
          basedir: /usr/local/util/spring-cloud/basedir
  rabbitmq:
    host: 47.101.197.240
    port: 5672
    password: guest
    username: guest
  # 允许/actuator/bus-refresh接口被外部调用
management:
  endpoints:
    web:
      expose: "*"

eureka:
  client:
    serviceUrl:
      defaultZone:  http://47.101.197.240:8761/eureka/
    instance-info-replication-interval-seconds: 10
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}  #固定端口
    lease-renewal-interval-in-seconds: 10  #每隔几秒告诉eureka服务器我还存活，用于心跳检测
    lease-expiration-duration-in-seconds: 10 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/doc.html #固定端口
    ip-address: 47.101.197.240
    non-secure-port: 8090